services:
  redis:
    image: redis:7
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "6380:6379"

  docker-cloner:
    image: abhibr/deployr-docker-cloner:latest
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./output:/app/output
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379

  docker-pull-and-builder:
    image: abhibr/deployr-docker-pull-and-builder:latest
    restart: always
    ports:
      - "8082:8082"
    volumes:
      - ./output:/app/output
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - OUTPUT_BASE_PATH=/root/deployr/output

  static-server:
    image: abhibr/deployr-static-server:latest
    restart: always
    depends_on:
      - redis
    ports:
      - "8081:8081"
    environment:
      - REDIS_URL=redis://redis:6379

volumes:
  redis_data:
