"use client"
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Agor_2012 (https://sketchfab.com/Agor_)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-man-working-at-a-table-with-a-laptop-be6b2404359c474fb0ed148e1882516e
Title: Low poly man working at a table with a laptop
*/

import React, { useEffect, useRef, useState } from 'react'
import { useGLTF,useAnimations } from '@react-three/drei'
import * as THREE from 'three'

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export default function Model(props: any) {
  const group = useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF('/scene.gltf')
  const { actions } = useAnimations(animations, group)
  const [isPlaying, setIsPlaying] = useState(false)
  const timeoutRef = useRef<NodeJS.Timeout | null>(null)

  useEffect(() => {
    const action = actions?.Animation
    if (action) {
      action.setLoop(THREE.LoopOnce, 1) // Play only once
      action.clampWhenFinished = true
      action.timeScale = 1.5 // Speed up animation slightly
    }

    return () => {
      if (timeoutRef.current) clearTimeout(timeoutRef.current)
    }
  }, [actions])

  const playWithDelayLoop = () => {
    const action = actions?.Animation
    if (!action) return

    action.reset().play()
    setIsPlaying(true)

    action.getMixer().addEventListener('finished', () => {
      setIsPlaying(false)

      // Add 2s delay before playing again
      timeoutRef.current = setTimeout(() => {
        if (!isPlaying) playWithDelayLoop()
      }, 1000)
    })
  }

  const handlePointerOver = () => {
    if (!isPlaying) playWithDelayLoop()
  }

  const handlePointerOut = () => {
    actions?.Animation?.stop()
    setIsPlaying(false)
    if (timeoutRef.current) clearTimeout(timeoutRef.current)
  }


  return (
    <group ref={group} {...props} dispose={null}
      onPointerOver={handlePointerOver}
      onPointerOut={handlePointerOut}
    >
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          userData={{ name: 'Sketchfab_model' }}>
          <group name="root" userData={{ name: 'root' }}>
            <group
              name="GLTF_SceneRootNode"
              rotation={[Math.PI / 2, 0, 0]}
              userData={{ name: 'GLTF_SceneRootNode' }}>
              <group
                name="Empty_1"
                position={[0.004, 3.004, -0.088]}
                userData={{ name: 'Empty_1' }}>
                <group
                  name="chair_0"
                  position={[-0.041, -0.885, 0.123]}
                  scale={0.754}
                  userData={{ name: 'chair_0' }}>
                  <mesh
                    name="Object_5"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_5.geometry}
                    material={materials['Material.006']}
                    userData={{ name: 'Object_5' }}
                  />
                  <mesh
                    name="Object_6"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_6.geometry}
                    material={materials['Material.005']}
                    userData={{ name: 'Object_6' }}
                  />
                  <mesh
                    name="Object_7"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_7.geometry}
                    material={materials['Material.010']}
                    userData={{ name: 'Object_7' }}
                  />
                  <mesh
                    name="Object_8"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_8.geometry}
                    material={materials['Material.003']}
                    userData={{ name: 'Object_8' }}
                  />
                </group>
              </group>
              <group
                name="book_5"
                position={[-3.464, 4.562, 2.562]}
                rotation={[0, -0.177, 0]}
                scale={0.755}
                userData={{ name: 'book_5' }}>
                <mesh
                  name="Object_10"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_10.geometry}
                  material={materials['Material.016']}
                  userData={{ name: 'Object_10' }}
                />
                <mesh
                  name="Object_11"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_11.geometry}
                  material={materials['Material.015']}
                  userData={{ name: 'Object_11' }}
                />
              </group>
              <group
                name="book2_6"
                position={[-3.448, 4.379, 2.795]}
                rotation={[0, -0.026, 0]}
                scale={0.755}
                userData={{ name: 'book2_6' }}>
                <mesh
                  name="Object_13"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_13.geometry}
                  material={materials['Material.014']}
                  userData={{ name: 'Object_13' }}
                />
                <mesh
                  name="Object_14"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_14.geometry}
                  material={materials['Material.016']}
                  userData={{ name: 'Object_14' }}
                />
              </group>
              <group
                name="laptop_8"
                position={[0.13, 4.352, 3.552]}
                rotation={[-Math.PI, 0, -Math.PI]}
                scale={[0.174, 0.127, 0.174]}
                userData={{ name: 'laptop_8' }}>
                <mesh
                  name="Object_16"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_16.geometry}
                  material={materials['Material.001']}
                  userData={{ name: 'Object_16' }}
                />
                <mesh
                  name="Object_17"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_17.geometry}
                  material={materials['Material.009']}
                  userData={{ name: 'Object_17' }}
                />
                <group
                  name="Plane002_7"
                  position={[0, 0.143, -3.649]}
                  rotation={[1.285, 0, 0]}
                  scale={[1, 1.031, 1.348]}
                  userData={{ name: 'Plane.002_7' }}>
                  <mesh
                    name="Object_19"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_19.geometry}
                    material={materials['Material.001']}
                    userData={{ name: 'Object_19' }}
                  />
                  <mesh
                    name="Object_20"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_20.geometry}
                    material={materials['Material.009']}
                    userData={{ name: 'Object_20' }}
                  />
                  <mesh
                    name="Object_21"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_21.geometry}
                    material={materials.material_0}
                    userData={{ name: 'Object_21' }}
                  />
                </group>
              </group>
              <group name="Armature_92" userData={{ name: 'Armature_92' }}>
                <group name="GLTF_created_0" userData={{ name: 'GLTF_created_0' }}>
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <skinnedMesh
                    name="Object_116"
                    geometry={nodes.Object_116.geometry}
                    material={materials.boots}
                    skeleton={nodes.Object_116.skeleton}
                    userData={{ name: 'Object_116' }}
                  />
                  <skinnedMesh
                    name="Object_117"
                    geometry={nodes.Object_117.geometry}
                    material={materials.pants}
                    skeleton={nodes.Object_117.skeleton}
                    userData={{ name: 'Object_117' }}
                  />
                  <skinnedMesh
                    name="Object_118"
                    geometry={nodes.Object_118.geometry}
                    material={materials.shirt}
                    skeleton={nodes.Object_118.skeleton}
                    userData={{ name: 'Object_118' }}
                  />
                  <skinnedMesh
                    name="Object_119"
                    geometry={nodes.Object_119.geometry}
                    material={materials.skin}
                    skeleton={nodes.Object_119.skeleton}
                    userData={{ name: 'Object_119' }}
                  />
                  <skinnedMesh
                    name="Object_120"
                    geometry={nodes.Object_120.geometry}
                    material={materials.mouth}
                    skeleton={nodes.Object_120.skeleton}
                    userData={{ name: 'Object_120' }}
                  />
                  <group name="body_91_correction" userData={{ name: 'body_91_correction' }}>
                    <group name="body_91" userData={{ name: 'body_91' }} />
                  </group>
                </group>
              </group>
              <group
                name="Plane_93"
                position={[2.665, 4.425, 3.065]}
                rotation={[0, 0.362, 0]}
                scale={0.784}
                userData={{ name: 'Plane_93' }}>
                <mesh
                  name="Object_122"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_122.geometry}
                  material={materials.shirt}
                  userData={{ name: 'Object_122' }}
                />
              </group>
              <group
                name="headphones_94"
                position={[-3.014, 4.794, 4.105]}
                rotation={[1.817, 0.093, 0.355]}
                scale={0.317}
                userData={{ name: 'headphones_94' }}>
                <mesh
                  name="Object_124"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_124.geometry}
                  material={materials['Material.009']}
                  userData={{ name: 'Object_124' }}
                />
                <mesh
                  name="Object_125"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_125.geometry}
                  material={materials['Material.006']}
                  userData={{ name: 'Object_125' }}
                />
                <mesh
                  name="Object_126"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_126.geometry}
                  material={materials['Material.003']}
                  userData={{ name: 'Object_126' }}
                />
              </group>
              <group
                name="lamp_95"
                position={[3.131, 4.34, 4.844]}
                rotation={[-Math.PI, 0.705, -Math.PI]}
                scale={0.885}
                userData={{ name: 'lamp_95' }}>
                <mesh
                  name="Object_128"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_128.geometry}
                  material={materials['Material.012']}
                  userData={{ name: 'Object_128' }}
                />
                <mesh
                  name="Object_129"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_129.geometry}
                  material={materials['Material.003']}
                  userData={{ name: 'Object_129' }}
                />
                <mesh
                  name="Object_130"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_130.geometry}
                  material={materials['Material.010']}
                  userData={{ name: 'Object_130' }}
                />
                <mesh
                  name="Object_131"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_131.geometry}
                  material={materials.emission}
                  userData={{ name: 'Object_131' }}
                />
              </group>
              <group
                name="mug_96"
                position={[-2.1, 4.284, 3.62]}
                rotation={[0, 1.383, 0]}
                scale={0.327}
                userData={{ name: 'mug_96' }}>
                <mesh
                  name="Object_133"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_133.geometry}
                  material={materials['Material.010']}
                  userData={{ name: 'Object_133' }}
                />
                <mesh
                  name="Object_134"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_134.geometry}
                  material={materials['Material.007']}
                  userData={{ name: 'Object_134' }}
                />
                <mesh
                  name="Object_135"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_135.geometry}
                  material={materials['Material.003']}
                  userData={{ name: 'Object_135' }}
                />
              </group>
              <group
                name="pencil_97"
                position={[2.599, 4.321, 3.159]}
                rotation={[-Math.PI / 2, Math.PI / 6, Math.PI]}
                scale={[-0.03, 0.349, 0.03]}
                userData={{ name: 'pencil_97' }}>
                <mesh
                  name="Object_137"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_137.geometry}
                  material={materials['Material.010']}
                  userData={{ name: 'Object_137' }}
                />
                <mesh
                  name="Object_138"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_138.geometry}
                  material={materials['Material.008']}
                  userData={{ name: 'Object_138' }}
                />
                <mesh
                  name="Object_139"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_139.geometry}
                  material={materials['Material.009']}
                  userData={{ name: 'Object_139' }}
                />
              </group>
              <group
                name="phone_98"
                position={[3.618, 4.308, 2.543]}
                rotation={[-Math.PI, -0.187, -Math.PI]}
                scale={0.296}
                userData={{ name: 'phone_98' }}>
                <mesh
                  name="Object_141"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_141.geometry}
                  material={materials['Material.009']}
                  userData={{ name: 'Object_141' }}
                />
                <mesh
                  name="Object_142"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_142.geometry}
                  material={materials['Material.006']}
                  userData={{ name: 'Object_142' }}
                />
              </group>
              <group
                name="table_107"
                position={[-0.3, 2.567, 4.17]}
                rotation={[-Math.PI, 0, -Math.PI]}
                scale={[-0.149, 1.865, 1.865]}
                userData={{ name: 'table_107' }}>
                <mesh
                  name="Object_144"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_144.geometry}
                  material={materials['Material.013']}
                  userData={{ name: 'Object_144' }}
                />
                <mesh
                  name="Object_145"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_145.geometry}
                  material={materials['Material.004']}
                  userData={{ name: 'Object_145' }}
                />
                <group
                  name="Cube001_103"
                  position={[-18.215, 0.576, 0.203]}
                  scale={[0.846, 1, 1]}
                  userData={{ name: 'Cube.001_103' }}>
                  <mesh
                    name="Object_147"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_147.geometry}
                    material={materials['Material.002']}
                    userData={{ name: 'Object_147' }}
                  />
                  <mesh
                    name="Object_148"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_148.geometry}
                    material={materials['Material.013']}
                    userData={{ name: 'Object_148' }}
                  />
                </group>
                <group
                  name="Cube002_104"
                  position={[-18.215, 0.08, 0.203]}
                  scale={[0.846, 1, 1]}
                  userData={{ name: 'Cube.002_104' }}>
                  <mesh
                    name="Object_150"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_150.geometry}
                    material={materials['Material.002']}
                    userData={{ name: 'Object_150' }}
                  />
                  <mesh
                    name="Object_151"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_151.geometry}
                    material={materials['Material.013']}
                    userData={{ name: 'Object_151' }}
                  />
                </group>
                <group
                  name="Cube004_105"
                  position={[-18.215, -0.417, 0.248]}
                  scale={[0.846, 1, 1]}
                  userData={{ name: 'Cube.004_105' }}>
                  <mesh
                    name="Object_153"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_153.geometry}
                    material={materials['Material.002']}
                    userData={{ name: 'Object_153' }}
                  />
                  <mesh
                    name="Object_154"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_154.geometry}
                    material={materials['Material.013']}
                    userData={{ name: 'Object_154' }}
                  />
                </group>
                <group
                  name="Cube005_106"
                  position={[-18.215, -0.913, 0.203]}
                  scale={[0.846, 1, 1]}
                  userData={{ name: 'Cube.005_106' }}>
                  <mesh
                    name="Object_156"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_156.geometry}
                    material={materials['Material.002']}
                    userData={{ name: 'Object_156' }}
                  />
                  <mesh
                    name="Object_157"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_157.geometry}
                    material={materials['Material.013']}
                    userData={{ name: 'Object_157' }}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
